# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ical_builder}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marshall Roch"]
  s.date = %q{2011-03-28}
  s.email = %q{marshall@mroch.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "ical_builder.gemspec",
    "init.rb",
    "lib/ical_builder.rb",
    "lib/ical_template.rb",
    "rails/init.rb",
    "test/ical_builder_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/mroch/ical_builder}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{An iCalendar generator in Ruby, modelled after Jim Weirich's Builder}
  s.test_files = [
    "test/ical_builder_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<blankslate>, [">= 0"])
    else
      s.add_dependency(%q<blankslate>, [">= 0"])
    end
  else
    s.add_dependency(%q<blankslate>, [">= 0"])
  end
end

